# Fichier de config commun aux differentes applications clientes du Serveur de Config
server:
  application:
    conf:
      dir: ${user.dir}/logs
  use-forward-headers: true
  address: localhost
  port: 8081

spring:
  application:
    name: ocr
  session:
    store-type: none
webapp:
  actuator:
    username: admin
    password: admin
  security:
    restPrefix: ${webapp.url.services}/rest
  url:
    contextRoot: /ocr
    services:  ${webapp.url.contextRoot}/services