# Fichier de config commun aux differentes applications clientes du Serveur de Config
server:
  application:
    conf:
      dir: ${user.dir}/logs
  use-forward-headers: true
  address: localhost
  port: 8089

spring:
  application:
    name: ocr
  session:
    store-type: none
webapp:
  actuator:
    username: admin
    password: admin
  security:
    restPrefix: ${webapp.url.services}/rest
  url:
    contextRoot: /ocr
    services:  ${webapp.url.contextRoot}/services

management:
  context-path: /management
  security:
    enabled: false
endpoints:
  shutdown:
    enabled: true

datasource:
  ocr:
    host: localhost
    port: 5432
    dbname: ocr
    username: usrocr
    password: pwdocr
    maxPoolSize: 10
    minPoolSize: 3
    testQuery: select 1 from dual
    url: jdbc:postgresql://${datasource.ocr.host}:${datasource.ocr.port}/${datasource.ocr.dbname}
    jdbcDialect: org.hibernate.dialect.PostgreSQLDialect
hibernate:
  configuration:
    defaultSchema: ocr_default
    jdbcDialect: org.hibernate.dialect.PostgreSQLDialect
    schemas:
      schema_name_ssi: ocr_default