package com.perso.pojo.residus;

public class MoleculesLmsList extends MoleculesList {

    @Override
    protected void fillMap() {
        this.values.put("2-(1-naphtyl)acetamide (A)",0.01);
        this.values.put("6-benzyladenine (A)",0.01);
        this.values.put("abamectine (A)",0.01);
        this.values.put("acephate (A)",0.01);
        this.values.put("acetamiprid (A)",0.01);
        this.values.put("acibenzolar- S- methyl (sum of acibenzolar- S- methyl and acibenzolar acid (free and conjugated), expressed as acibenzolar- S- methyl)",0.01);
        this.values.put("acibenzolar-acid",0.05);
        this.values.put("acibenzolar-S-methyl (A)",0.01);
        this.values.put("aldicarb (A)",0.01);
        this.values.put("aldicarb - sulfon (A)",0.01);
        this.values.put("aldicarb - sulfoxide (A)",0.01);
        this.values.put("aldicarb (sum of aldicarb, its sulfoxide and its sulfone, expressed as aldicarb) (A)",0.01);
        this.values.put("allethrin (A)",0.01);
        this.values.put("ametoctradin (A)",0.01);
        this.values.put("amétryne (A)",0.01);
        this.values.put("amidosulfuron (A)",0.01);
        this.values.put("amisulbrom (A)",0.01);
        this.values.put("asulame (A)",0.01);
        this.values.put("atrazine (A)",0.01);
        this.values.put("azadirachtin (A)",0.01);
        this.values.put("azamethiphos (A)",0.01);
        this.values.put("azimsulfuron (A)",0.01);
        this.values.put("azinphos-ethyl (A)",0.01);
        this.values.put("azinphos-methyl (A)",0.01);
        this.values.put("azoxystrobine (A)",0.01);
        this.values.put("beflubutamid (A)",0.01);
        this.values.put("bendiocarb (A)",0.01);
        this.values.put("bensulfuron-methyl (A)",0.01);
        this.values.put("benthiavalicarb (A)",0.01);
        this.values.put("bispyribac-sodium (A)",0.01);
        this.values.put("bitertanol (A)",0.01);
        this.values.put("bixafen (A)",0.01);
        this.values.put("boscalid (A)",0.02);
        this.values.put("bromacil (A)",0.01);
        this.values.put("bromuconazole (sum of diasteroisomers) (A)",0.01);
        this.values.put("bupirimate (A)",0.01);
        this.values.put("buprofézine (A)",0.01);
        this.values.put("carbaryl (A)",0.01);
        this.values.put("carbendazim and benomyl (sum of benomyl and carbendazim expressed as carbendazim) (A)",0.01);
        this.values.put("carbétamide (A)",0.01);
        this.values.put("carbofuran (A)",0.01);
        this.values.put("carbofuran (3-OH-) (A)",0.01);
        this.values.put("carbofuran (sum of carbofuran (including any carbofuran generated from carbosulfan, benfuracarb or furathiocarb) and 3-OH carbofuran expressed as carb (A)",0.01);
        this.values.put("carbosulfan (A)",0.01);
        this.values.put("carboxin (A)",0.01);
        this.values.put("carfentrazone-ethyl (determined as carfentrazone and expressed as carfentrazone-ethyl) (A)",0.01);
        this.values.put("chlorantraniliprole (DPX E-2Y45) (A)",0.01);
        this.values.put("chlorbromuron (A)",0.01);
        this.values.put("chlorfenvinphos (A)",0.01);
        this.values.put("chlorfluazuron (A)",0.01);
        this.values.put("chloridazon (A)",0.01);
        this.values.put("chlorotoluron (A)",0.01);
        this.values.put("chloroxuron (A)",0.01);
        this.values.put("chlorsulfuron (A)",0.01);
        this.values.put("cinerin I",0.01);
        this.values.put("cinerin II",0.01);
        this.values.put("clethodim (sum of sethoxydim and clethodim including degradation products calculated as sethoxydim) (A)",0.01);
        this.values.put("cléthodime (A)",0.01);
        this.values.put("clodinafop (A)",0.01);
        this.values.put("clodinafop and its Sisomers and their salts, expressed as clodinafop (A)",0.01);
        this.values.put("clodinafop-propargyl (A)",0.01);
        this.values.put("clofentezine (A)",0.01);
        this.values.put("clomazone (A)",0.01);
        this.values.put("clothianidin (A)",0.01);
        this.values.put("cyantraniliprole (A)",0.01);
        this.values.put("cyazofamid (A)",0.01);
        this.values.put("cycloxidime (A)",0.01);
        this.values.put("cyflumetofen (A)",0.01);
        this.values.put("cymiazole (A)",0.01);
        this.values.put("cymoxanil (A)",0.01);
        this.values.put("cyproconazole (A)",0.01);
        this.values.put("cyprodinyl (A)",0.01);
        this.values.put("dazomet (A)",0.01);
        this.values.put("demethon-s-methyl (A)",0.01);
        this.values.put("demeton-S-methyl-sulfon (A)",0.01);
        this.values.put("diafenthiuron",0.01);
        this.values.put("dicrotophos (A)",0.01);
        this.values.put("diéthofencarb (A)",0.01);
        this.values.put("difénoconazole (A)",0.01);
        this.values.put("diflubenzuron (A)",0.01);
        this.values.put("diflufénicanil (A)",0.01);
        this.values.put("dimefox (A)",0.01);
        this.values.put("Dimethenamid including other mixtures of constituent isomers including dimethenamidP (sum of isomers) (A)",0.01);
        this.values.put("dimethoate (A)",0.01);
        this.values.put("dimethoate (sum of dimethoate and omethoate expressed as dimethoate) (A)",0.01);
        this.values.put("dimethomorph (sum of isomers) (A)",0.01);
        this.values.put("dimoxystrobin (A)",0.01);
        this.values.put("diniconazole (A)",0.01);
        this.values.put("dinotefuran (A)",0.01);
        this.values.put("disulfoton (A)",0.01);
        this.values.put("disulfoton (sum of disulfoton, disulfoton sulfoxide and disulfoton sulfone expressed as disulfoton) (A)",0.01);
        this.values.put("disulfoton-sulfone (A)",0.01);
        this.values.put("disulfoton-sulfoxide (A)",0.01);
        this.values.put("diuron (A)",0.01);
        this.values.put("dodemorph (A)",0.01);
        this.values.put("dodine (A)",0.02);
        this.values.put("emamectin benzoate B1a (A)",0.01);
        this.values.put("emamectin benzoate B1a, expressed as emamectin (A)",0.01);
        this.values.put("emamectin benzoate B1b (A)",0.01);
        this.values.put("epoxiconazole (A)",0.01);
        this.values.put("ethametsulfuron-methyl (A)",0.01);
        this.values.put("ethiofencarb (A)",0.01);
        this.values.put("ethirimol (A)",0.01);
        this.values.put("ethoxysulfuron (A)",0.01);
        this.values.put("etoxazole (A)",0.01);
        this.values.put("fénamidone (A)",0.01);
        this.values.put("fenamiphos (A)",0.01);
        this.values.put("fenamiphos - sulfone (A)",0.01);
        this.values.put("fenamiphos - sulfoxide (A)",0.01);
        this.values.put("fenamiphos (sum of fenamiphos and its sulphoxide and sulphone expressed as fenamiphos) (A)",0.01);
        this.values.put("fénarimol (A)",0.01);
        this.values.put("fénazaquin (A)",0.01);
        this.values.put("fenbuconazole (A)",0.01);
        this.values.put("fenhexamid (A)",0.01);
        this.values.put("fenobucarb (A)",0.01);
        this.values.put("fenoxaprop-P (A)",0.01);
        this.values.put("fenoxaprop-P-éthyl (A)",0.01);
        this.values.put("fénoxycarb (A)",0.01);
        this.values.put("fenpiclonil (A)",0.01);
        this.values.put("fenpropidin (sum of fenpropidin and its salts, expressed as fenpropidin) (A)",0.01);
        this.values.put("fenpyrazamine (A)",0.01);
        this.values.put("fenpyroximate (A)",0.01);
        this.values.put("fensulfothion (A)",0.01);
        this.values.put("fensulfothion-oxon (A)",0.01);
        this.values.put("fensulfothion-oxon-sulfon (A)",0.01);
        this.values.put("fensulfothion-sulfon (A)",0.01);
        this.values.put("fenthion (A)",0.01);
        this.values.put("fenthion - sulfon (A)",0.05);
        this.values.put("fenthion - sulfoxide (A)",0.01);
        this.values.put("Fenthion (fenthion and its oxigen analogue, their sulfoxides and sulfone expressed as parent) (A)",0.01);
        this.values.put("fenthion-oxon (A)",0.01);
        this.values.put("fenthion-oxon-sulfone (A)",0.01);
        this.values.put("fenthion-oxon-sulfoxid (A)",0.01);
        this.values.put("fenuron (A)",0.01);
        this.values.put("flazasulfuron (A)",0.01);
        this.values.put("flonicamid (A)",0.01);
        this.values.put("florasulam (A)",0.01);
        this.values.put("fluazifop-P (A)",0.01);
        this.values.put("fluazifop-P - butyl (A)",0.01);
        this.values.put("fluazifop-P-butyl (fluazifop acid (free )) (A)",0.01);
        this.values.put("fluazinam (A)",0.02);
        this.values.put("flubendiamide (A)",0.01);
        this.values.put("flufénacet (A)",0.01);
        this.values.put("flufénoxuron (A)",0.01);
        this.values.put("fluometuron",0.02);
        this.values.put("fluopicolide (A)",0.01);
        this.values.put("fluopyram (A)",0.01);
        this.values.put("fluoxastrobin (A)",0.01);
        this.values.put("flupyradifurone (A)",0.01);
        this.values.put("flupyrsulfuron-méthyl (A)",0.01);
        this.values.put("fluquinconazole (A)",0.01);
        this.values.put("flurochloridon (A)",0.01);
        this.values.put("fluroxypyr",0.02);
        this.values.put("flurtamone (A)",0.01);
        this.values.put("flusilazole (A)",0.01);
        this.values.put("flutolanil (A)",0.01);
        this.values.put("flutriafol (A)",0.01);
        this.values.put("fluxapyroxad (A)",0.01);
        this.values.put("FM-6 (A)",0.01);
        this.values.put("fonofos (A)",0.01);
        this.values.put("foramsulfuron (A)",0.01);
        this.values.put("forchlorfenuron (A)",0.01);
        this.values.put("fosthiazate (A)",0.01);
        this.values.put("fuberidazole (A)",0.01);
        this.values.put("furalaxyl (A)",0.01);
        this.values.put("furathiocarbe (A)",0.01);
        this.values.put("haloxyfop - R (A)",0.01);
        this.values.put("haloxyfop including haloxyfop-R (HaloxyfopR methyl ester and haloxyfop-R expressed as haloxyfop-R) (A)",0.01);
        this.values.put("haloxyfop-methyl (A)",0.01);
        this.values.put("hexaconazole (A)",0.01);
        this.values.put("hexazinone (A)",0.01);
        this.values.put("héxythiazox (A)",0.01);
        this.values.put("imazalil (A)",0.01);
        this.values.put("imazamox",0.01);
        this.values.put("imazapyr",0.01);
        this.values.put("imazaquine",0.01);
        this.values.put("imazosulfuron (A)",0.01);
        this.values.put("imidaclopride (A)",0.01);
        this.values.put("indoxacarb (sum of indoxacarb and its R enantiomer) (A)",0.01);
        this.values.put("iodosulfuron-methyl (iodosulfuron-methyl including salts, expressed as iodosulfuron-methyl) (A)",0.01);
        this.values.put("iprobenfos (A)",0.01);
        this.values.put("iprodione (A)",0.01);
        this.values.put("iprovalicarbe (A)",0.01);
        this.values.put("isoprothiolane (A)",0.01);
        this.values.put("isoproturon (IPU) (A)",0.01);
        this.values.put("isopyrazam (A)",0.01);
        this.values.put("isoxaben (A)",0.01);
        this.values.put("krésoxim-méthyl (A)",0.01);
        this.values.put("lenacil (A)",0.01);
        this.values.put("linuron (A)",0.01);
        this.values.put("lufénuron (A)",0.02);
        this.values.put("mandipropamid (A)",0.01);
        this.values.put("mépanipyrim (A)",0.01);
        this.values.put("mesosulfuron-methyl (A)",0.01);
        this.values.put("metaflumizone (sum of E- and Z- isomers) (A)",0.01);
        this.values.put("metalaxyl and metalaxylM (metalaxyl including other mixtures of constituent isomers including metalaxyl-M (sum of isomers)) (A)",0.01);
        this.values.put("métamitrone (A)",0.01);
        this.values.put("metazachlor (A)",0.01);
        this.values.put("metconazole (sum of isomers) (A)",0.01);
        this.values.put("méthabenzthiazuron (A)",0.01);
        this.values.put("méthamidophos (A)",0.01);
        this.values.put("methiocarb (A)",0.01);
        this.values.put("methiocarb (sum of methiocarb and methiocarb sulfoxide and sulfone, expressed as methiocarb) (A)",0.01);
        this.values.put("methiocarb-sulfon (A)",0.01);
        this.values.put("methiocarb-sulfoxide (A)",0.01);
        this.values.put("metholachlor and metholachlor-S (metholachlor including other mixtures of constituent isomers including S-metholachlor (sum of isomers)) (A)",0.01);
        this.values.put("methomyl (A)",0.01);
        this.values.put("méthoxyfenozide (A)",0.01);
        this.values.put("metobromuron (A)",0.01);
        this.values.put("métosulame (A)",0.01);
        this.values.put("métoxuron (A)",0.01);
        this.values.put("metsulfuron-méthyl (A)",0.01);
        this.values.put("molinate (A)",0.01);
        this.values.put("monocrotophos (A)",0.01);
        this.values.put("monolinuron (A)",0.02);
        this.values.put("myclobutanil (A)",0.01);
        this.values.put("napropamide (A)",0.01);
        this.values.put("nicosulfuron (A)",0.01);
        this.values.put("nitenpyram (A)",0.01);
        this.values.put("novaluron (A)",0.01);
        this.values.put("nuarimol (A)",0.01);
        this.values.put("ofurace (A)",0.01);
        this.values.put("omethoate (A)",0.01);
        this.values.put("oxadixyl (A)",0.01);
        this.values.put("oxamyl (A)",0.01);
        this.values.put("oxycarboxin (A)",0.01);
        this.values.put("oxydemeton-methyl (A)",0.01);
        this.values.put("oxydemeton-methyl (sum of oxydemeton-methyl and demeton-Smethylsulfone expressed as oxydemeton-methyl) (A)",0.01);
        this.values.put("paclobutrazol (A)",0.01);
        this.values.put("penconazole (A)",0.01);
        this.values.put("pencycuron (A)",0.01);
        this.values.put("penoxsulam (A)",0.01);
        this.values.put("pethoxamid (A)",0.01);
        this.values.put("phenmedipham (A)",0.01);
        this.values.put("phenthoate (A)",0.01);
        this.values.put("phosphamidon (A)",0.01);
        this.values.put("phoxim (A)",0.01);
        this.values.put("picolinafène (A)",0.01);
        this.values.put("picoxystrobin (A)",0.01);
        this.values.put("pinoxaden (A)",0.01);
        this.values.put("pirimicarb (A)",0.01);
        this.values.put("prochloraze (A)",0.01);
        this.values.put("profenofos (A)",0.01);
        this.values.put("promecarb (A)",0.01);
        this.values.put("propamocarb (sum of propamocarb and its salt expressed as propamocarb) (A)",0.01);
        this.values.put("propanil (A)",0.01);
        this.values.put("propaquizafop (A)",0.01);
        this.values.put("propazin (A)",0.01);
        this.values.put("propham (IPC) (A)",0.01);
        this.values.put("propiconazole (sum of isomers) (A)",0.01);
        this.values.put("propoxur (A)",0.01);
        this.values.put("propyzamide (A)",0.01);
        this.values.put("proquinazid (A)",0.01);
        this.values.put("prosulfocarbe (A)",0.01);
        this.values.put("prosulfuron (A)",0.01);
        this.values.put("prothioconazole: prothioconazole-dethio (sum of isomers) (A)",0.01);
        this.values.put("pymétrozine (A)",0.01);
        this.values.put("pyraclostrobine (A)",0.01);
        this.values.put("pyraflufen-éthyl (A)",0.01);
        this.values.put("pyrethrin I",0.01);
        this.values.put("pyrethrin II",0.01);
        this.values.put("pyrethrins",0.01);
        this.values.put("pyridafol",0.01);
        this.values.put("pyridalyl (A)",0.01);
        this.values.put("pyridaphenthion (A)",0.01);
        this.values.put("pyridate",0.01);
        this.values.put("Pyridate (sum of pyridate, its hydrolysis product CL 9673 (6-chloro-4hydroxy-3phenylpyridazin) and hydrolysable conjugates of CL 9673 expressed as p",0.01);
        this.values.put("pyrifénox (A)",0.01);
        this.values.put("pyriméthanil (A)",0.01);
        this.values.put("pyriofenone (A)",0.01);
        this.values.put("quinclorac (A)",0.01);
        this.values.put("quinmérac",0.01);
        this.values.put("quinoxyfène (A)",0.01);
        this.values.put("quizalofop, incl. quizalofop-P (A)",0.01);
        this.values.put("quizalofop-éthyl (A)",0.01);
        this.values.put("rimsulfuron (A)",0.01);
        this.values.put("roténone (A)",0.01);
        this.values.put("séthoxydime (A)",0.01);
        this.values.put("simazine (A)",0.01);
        this.values.put("spinetoram (A)",0.01);
        this.values.put("spinetoram I (A)",0.01);
        this.values.put("spinetoram II (A)",0.01);
        this.values.put("spinosad: sum of spinosyn A and spinosyn D, expressed as spinosad (A)",0.01);
        this.values.put("spinosyn A (A)",0.01);
        this.values.put("spinosyn D (A)",0.01);
        this.values.put("spirotetramat (A)",0.01);
        this.values.put("spirotetramat and its 4 metabolites BYI08330enol, BYI08330ketohydroxy, BYI08330monohydroxy, and BYI08330 enol-glucoside, expressed as spirotetramat (A)",0.01);
        this.values.put("spirotetramat-enol (A)",0.01);
        this.values.put("spirotetramat-enolglucoside (A)",0.01);
        this.values.put("spirotetramat-keto-hydrox (A)",0.01);
        this.values.put("spirotetramat-monohydrox (A)",0.01);
        this.values.put("spiroxamine (sum of isomers) (A)",0.01);
        this.values.put("sulfosulfuron (A)",0.01);
        this.values.put("sulfoxaflor (A)",0.01);
        this.values.put("tebuconazole (A)",0.01);
        this.values.put("tébufenozide (A)",0.01);
        this.values.put("tébufenpyrad (A)",0.01);
        this.values.put("tepraloxydim (A)",0.01);
        this.values.put("terbufos (A)",0.01);
        this.values.put("terbufos-sulfon (A)",0.01);
        this.values.put("terbufos-sulfoxide (A)",0.01);
        this.values.put("tétraconazole (A)",0.01);
        this.values.put("tetramethrine (A)",0.01);
        this.values.put("thiabendazole (A)",0.01);
        this.values.put("thiacloprid (A)",0.01);
        this.values.put("thiametoxam (A)",0.01);
        this.values.put("thifensulfuron-méthyle (A)",0.01);
        this.values.put("thiobencarb (A)",0.01);
        this.values.put("thiodicarb (A)",0.01);
        this.values.put("thionazine (A)",0.01);
        this.values.put("thiophanate-methyl (A)",0.01);
        this.values.put("triadimefon and triadimenol (sum of triadimefon and triadimenol) (A)",0.01);
        this.values.put("triadiméfone (A)",0.01);
        this.values.put("triadimenol (A)",0.01);
        this.values.put("triasulfuron (A)",0.01);
        this.values.put("triazophos (A)",0.01);
        this.values.put("trichlorfon (A)",0.02);
        this.values.put("tricyclazole (A)",0.01);
        this.values.put("tridemorphe (A)",0.01);
        this.values.put("trifloxystrobin (A)",0.01);
        this.values.put("triflumizole (A)",0.01);
        this.values.put("triflumizole (A)",0.01);
        this.values.put("triflumuron (A)",0.01);
        this.values.put("triforine (A)",0.01);
        this.values.put("trinexapac (sum of trinexapac (acid) and its salts, expressed as trinexapac) (A)",0.02);
        this.values.put("triticonazole (A)",0.01);
        this.values.put("valifenalate (A)",0.01);
        this.values.put("vamidothion (A)",0.01);
        this.values.put("zoxamide (A)",0.01);
    }
}
