package com.perso.pojo.residus;

public class MoleculesGmsList extends MoleculesList {

    @Override
    protected void fillMap() {
        this.values.put("1,4-dimethylnaphthalene",0.01);
        this.values.put("2-phenylphenol (ortho-) (A)",0.05);
        this.values.put("acetochlor (A)",0.01);
        this.values.put("aclonifen (A)",0.01);
        this.values.put("acrinathrine (A)",0.01);
        this.values.put("alachlor (A)",0.01);
        this.values.put("aldrin and dieldrin (aldrin and dieldrin combined expressed as dieldrin) (A)",0.01);
        this.values.put("aldrine (A)",0.01);
        this.values.put("anthraquinone (A)",0.01);
        this.values.put("benalaxyl including other mixtures of constituent isomers including benalaxyl-M (sum of isomers) (A)",0.01);
        this.values.put("benfluralin (A)",0.01);
        this.values.put("benzoylprop-ethyl (A)",0.01);
        this.values.put("bifenazate",0.01);
        this.values.put("bifénox (A)",0.01);
        this.values.put("bifenthrine (A)",0.01);
        this.values.put("biphenyl (A)",0.1);
        this.values.put("bromophos (bromophosmethyl) (A)",0.01);
        this.values.put("bromophos-ethyl (A)",0.01);
        this.values.put("bromopropylate (A)",0.01);
        this.values.put("butachlor (A)",0.01);
        this.values.put("butafenacil (A)",0.01);
        this.values.put("butralin (A)",0.01);
        this.values.put("butylate (A)",0.01);
        this.values.put("cadusafos (A)",0.01);
        this.values.put("captan",0.02);
        this.values.put("captan (Sum of captan and THPI, expressed as captan)",0.02);
        this.values.put("carbophenothion (A)",0.01);
        this.values.put("chinomethionate (A)",0.01);
        this.values.put("chlorbufam (A)",0.01);
        this.values.put("chlordane (sum of cis- and trans-chlordane) (A)",0.01);
        this.values.put("chlorfénapyr (A)",0.01);
        this.values.put("chlorfenson (A)",0.01);
        this.values.put("chlorméphos (A)",0.01);
        this.values.put("chlorobenside (A)",0.01);
        this.values.put("chlorobenzilate (A)",0.01);
        this.values.put("chloroneb (A)",0.01);
        this.values.put("chlorothalonil",0.01);
        this.values.put("chlorpropham (A)",0.01);
        this.values.put("chlorpyriphos-éthyl (A)",0.01);
        this.values.put("chlorpyriphos-méthyl (A)",0.01);
        this.values.put("chlorthal-dimethyl (DCPA) (A)",0.01);
        this.values.put("chlozolinate (A)",0.01);
        this.values.put("coumaphos (A)",0.01);
        this.values.put("crimidine (A)",0.01);
        this.values.put("cyanophenphos (A)",0.01);
        this.values.put("cycloate (A)",0.01);
        this.values.put("cyflufenamid: sum of cyflufenamid (Z-isomer) and its E-isomer (A)",0.01);
        this.values.put("cyfluthrin (cyfluthrin including other mixtures of constituent isomers (sum of isomers)) (A)",0.01);
        this.values.put("cyhalofop-butyl (A)",0.01);
        this.values.put("cyhalothrin (sum of gamma and lambda) (A)",0.01);
        this.values.put("cypermethrin (cypermethrin including other mixtures of constituent isomers (sum of isomers)) (A)",0.01);
        this.values.put("DBCP",0.1);
        this.values.put("DDD (o,p'-)",0.01);
        this.values.put("DDD(p,p'-) = TDE",0.01);
        this.values.put("DDE (op')",0.01);
        this.values.put("DDE (p,p')",0.01);
        this.values.put("DDT (op'-)",0.01);
        this.values.put("DDT (pp')",0.01);
        this.values.put("DDT (sum of p,p´-DDT, o,p´-DDT, p-p´-DDE and p,p´-TDE (DDD) expressed as DDT) (F)",0.01);
        this.values.put("DEET (N,N-diethyl-Mtoluamide) (A)",0.01);
        this.values.put("deltamethrin (cisdeltamethrin) (A)",0.01);
        this.values.put("desmetryne (A)",0.01);
        this.values.put("diazinon (A)",0.01);
        this.values.put("dichlobenil (A)",0.01);
        this.values.put("dichlofenthion (A)",0.01);
        this.values.put("dichlofluanide",0.01);
        this.values.put("dichlormide (A)",0.01);
        this.values.put("dichlorvos (A)",0.01);
        this.values.put("diclofop-methyl",0.01);
        this.values.put("diclofop-methyl (A)",0.01);
        this.values.put("dicloran (A)",0.01);
        this.values.put("dicofol (o,p')",0.01);
        this.values.put("dicofol (p,p')",0.01);
        this.values.put("dicofol (sum of p, p´ and o,p´ isomers)",0.01);
        this.values.put("dieldrin (A)",0.01);
        this.values.put("diméthachlore (A)",0.01);
        this.values.put("diphenamid (A)",0.01);
        this.values.put("diphenylamine (A)",0.05);
        this.values.put("ditalimfos (A)",0.01);
        this.values.put("DMST (A)",0.02);
        this.values.put("endosulfan (alfa-) (A)",0.01);
        this.values.put("endosulfan (beta-) (A)",0.01);
        this.values.put("endosulfan (sulphate-) (A)",0.01);
        this.values.put("endosulfan (sum of alpha- and beta-isomers and endosulfan-sulphate expresses as endosulfan) (A)",0.01);
        this.values.put("endrine (A)",0.01);
        this.values.put("EPN (A)",0.01);
        this.values.put("EPTC (ethyl dipropylthiocarbamate) (A)",0.01);
        this.values.put("esfenvalerate (A)",0.01);
        this.values.put("ethalfluralin (A)",0.01);
        this.values.put("ethion (A)",0.01);
        this.values.put("ethofumesate (A)",0.01);
        this.values.put("ethofumesate (sum of ethofumesate and the metabolite 2,3-dihydro-3,3-dimethyl-2-oxobenzofuran-5-yl methane sulphonate expressed as ethofumesate) (A)",0.01);
        this.values.put("ethofumesate-2-keto (A)",0.01);
        this.values.put("ethoprophos (A)",0.01);
        this.values.put("etofenprox (A)",0.01);
        this.values.put("etridiazole",0.05);
        this.values.put("etrimfos (A)",0.01);
        this.values.put("famoxadone (A)",0.01);
        this.values.put("fenchlorphos (A)",0.01);
        this.values.put("fenchlorphos",0.01);
        this.values.put("fenchlorphos-oxon",0.02);
        this.values.put("fenitrothion (A)",0.01);
        this.values.put("fenpropathrine (A)",0.01);
        this.values.put("fenpropimorphe (A)",0.01);
        this.values.put("fenson (A)",0.01);
        this.values.put("fenvalerate (A)",0.01);
        this.values.put("fenvalerate (sum of SS,RR,SR and RS) (A)",0.01);
        this.values.put("fipronil (A)",0.005);
        this.values.put("fipronil (sum fipronil + sulfone metabolite (MB46136) expressed as fipronil) (A)",0.005);
        this.values.put("fipronil-desulfinyl (A)",0.01);
        this.values.put("fipronil-sulfone (A)",0.005);
        this.values.put("flucythrinate (flucythrinate including other mixtures of constituent isomers (sum of isomers)) (A)",0.01);
        this.values.put("fludioxonil (A)",0.01);
        this.values.put("flumetralin (A)",0.01);
        this.values.put("formothion (A)",0.01);
        this.values.put("hch (alfa-) (A)",0.01);
        this.values.put("hch (beta-) (A)",0.01);
        this.values.put("HCH (delta-) (A)",0.01);
        this.values.put("HCH (epsilon-) (A)",0.01);
        this.values.put("heptachlor (A)",0.01);
        this.values.put("heptachlor (sum of heptachlor and heptachlor epoxide expressed as heptachlor) (A)",0.01);
        this.values.put("heptachlor epoxyde (A)",0.01);
        this.values.put("heptenophos (A)",0.01);
        this.values.put("hexachlorobenzene (HCB) (A)",0.01);
        this.values.put("hexachlorociclohexane (HCH), sum of isomers, except the gamma isomer (A)",0.01);
        this.values.put("iodofenfos (A)",0.01);
        this.values.put("ipconazole",0.01);
        this.values.put("isocarbofos (A)",0.01);
        this.values.put("isofenphos (-ethyl) (A)",0.01);
        this.values.put("isofenphos-methyl (A)",0.01);
        this.values.put("isoprocarb (A)",0.01);
        this.values.put("isopropalin (A)",0.01);
        this.values.put("lindane (Gamma-isomer of hexachlorocyclohexane (HCH)) (A)",0.01);
        this.values.put("malaoxon (A)",0.01);
        this.values.put("malathion (A)",0.01);
        this.values.put("malathion (sum of malathion and malaoxon expressed as malathion) (A)",0.01);
        this.values.put("mécarbam (A)",0.01);
        this.values.put("mépronil (A)",0.01);
        this.values.put("méthacrifos (A)",0.01);
        this.values.put("méthidathion (A)",0.01);
        this.values.put("methoprene (A)",0.01);
        this.values.put("méthoxychlore (A)",0.01);
        this.values.put("metrafenone (A)",0.01);
        this.values.put("métribuzin",0.01);
        this.values.put("mevinphos (sum of E- and Z-isomers) (A)",0.01);
        this.values.put("mirex (A)",0.01);
        this.values.put("nitrofène (A)",0.01);
        this.values.put("nitrothale-isopropyl (A)",0.01);
        this.values.put("oxadiargyl (A)",0.01);
        this.values.put("oxadiazon (A)",0.01);
        this.values.put("oxychlordane (A)",0.01);
        this.values.put("oxyfluorfen (A)",0.01);
        this.values.put("paraoxon-methyl",0.01);
        this.values.put("parathion (A)",0.01);
        this.values.put("parathion-methyl (A)",0.01);
        this.values.put("parathion-methyl (sum of parathion-methyl and paraoxon-methyl expressed as parathionmethyl)",0.01);
        this.values.put("pebulate (A)",0.01);
        this.values.put("pendimethalin (A)",0.01);
        this.values.put("pentachloraniline (PCA) (A)",0.01);
        this.values.put("pentachloroanisol (A)",0.01);
        this.values.put("penthiopyrade (A)",0.01);
        this.values.put("permethrin (sum of isomers) (A)",0.01);
        this.values.put("phenothrin (phenothrin including other mixtures of constituent isomers (sum of isomers)) (A)",0.02);
        this.values.put("phorate (A)",0.01);
        this.values.put("phosalone (A)",0.01);
        this.values.put("phosmet",0.01);
        this.values.put("phosmet (phosmet and phosmet oxon expressed as phosmet)",0.01);
        this.values.put("phosmet-oxon",0.05);
        this.values.put("pipéronyl-butoxyde (A)",0.01);
        this.values.put("pirimiphos-éthyl (A)",0.01);
        this.values.put("pirimiphos-méthyl (A)",0.01);
        this.values.put("pretilachlor (A)",0.01);
        this.values.put("procymidone (A)",0.01);
        this.values.put("profluralin (A)",0.01);
        this.values.put("prométryne (A)",0.01);
        this.values.put("propargite (A)",0.01);
        this.values.put("prothiofos (A)",0.01);
        this.values.put("pyrazophos (A)",0.01);
        this.values.put("pyridabène (A)",0.01);
        this.values.put("pyriproxyfène (A)",0.01);
        this.values.put("quinalphos (A)",0.01);
        this.values.put("quintozene (A)",0.01);
        this.values.put("quintozene (sum of quintozene and pentachloro-aniline expressed as quintozene) (A)",0.01);
        this.values.put("silafluofen (A)",0.01);
        this.values.put("silthiofam (A)",0.01);
        this.values.put("spirodiclofen (A)",0.01);
        this.values.put("spiromesifen (A)",0.01);
        this.values.put("sulfotep (A)",0.01);
        this.values.put("sulprofos (A)",0.01);
        this.values.put("tau-fluvalinate (A)",0.01);
        this.values.put("tecnazene (TCNB) (A)",0.01);
        this.values.put("téfluthrine (A)",0.01);
        this.values.put("terbacil (A)",0.01);
        this.values.put("terbuthylazine (A)",0.01);
        this.values.put("terbutryne (A)",0.01);
        this.values.put("tetrachlorvinphos (A)",0.01);
        this.values.put("tétradifon (A)",0.01);
        this.values.put("tetrahydrophtalimide",0.02);
        this.values.put("tiocarbazil (A)",0.01);
        this.values.put("tolclofos-méthyl (A)",0.01);
        this.values.put("tolfenpyrad (A)",0.01);
        this.values.put("tolylfluanid (sum of tolylfluanid and dimethylaminosulfotoluidi de expressed as tolylfluanid) (R)",0.02);
        this.values.put("tolylfluanide",0.02);
        this.values.put("transfluthrin (A)",0.01);
        this.values.put("tri-allate (A)",0.01);
        this.values.put("trifluralin (A)",0.01);
        this.values.put("vinclozolin (A)",0.01);
        this.values.put("vinclozolin - TOTAL (A)",0.01);
    }
}
