dossier:
  entrant: D:\\developpement\\ocr\\src\\main\\resources\\com\\perso\\
  temporaire: D:\\developpement\\temp
fichier:
  resultat: D:\\developpement\\ocr\\src\\main\\resources\\com\\Result.csv

ocr:
  #PROP_IMG_PREPROCESS_TYPE=custom|PROP_IMG_PREPROCESS_CUSTOM_CMDS=scale(10);PROP_IMG_PREPROCESS_CUSTOM_CMDS=invert();default()
  options: 
liste:
  fleurs:
    - Phacélie
    - Aigremoine eupatoire
    - Germandrée
    - Tamaris
    - Seringat
    - Tilleul
    - Nerprun
    - Sedum
    - Sumac
    - Phaoélie
    - Erable
    - Noyer
    - Phacélie
    - Colza
    - Marronnier
    - Ronce
    - Luzerne
    - Mélilot
    - Pin
    - Colz
    - Myosotis
    - Sainfoin
    - Lotier
    - Saule
    - Graminé
    - Fruitiers
    - Trèfle blanc
    - Erable
    - Papaver
    - Noyer
    - Réséda
    - Cornouiller sanguin
