dossier:
  entrant: D:\\dev\\ocr\\input\\
  temporaire: D:\\dev\\temp
  tesseract: D:\\dev\\ocr\\src\\main\\resources\\tessdata
liste:
  fleurs:
    - Phacélie
    - Aigremoine eupatoire
    - Germandrée
    - Tamaris
    - Seringat
    - Tilleul
    - Nerprun
    - Sedum
    - Sumac
    - Phaoélie
    - Erable
    - Noyer
    - Phacélie
    - Colza
    - Marronnier
    - Ronce
    - Luzerne
    - Mélilot
    - Pin
    - Colz
    - Myosotis
    - Sainfoin
    - Lotier
    - Saule
    - Graminé
    - Graminées
    - Fruitiers
    - Trèfle blanc
    - Erable
    - Papaver
    - Noyer
    - Réséda
    - Cornouiller sanguin
    - Pyracanthe
    - Cercis
    - Thym
