dossier:
  parent: D:\\dev
  entrant: ${dossier.parent}\\ocr\\input\\
  temporaire: ${dossier.parent}\\temp
  tesseract: ${dossier.parent}\\ocr\\config\\tessdata
  palynologie: palynologie
  residus: residus