dossier:
  parent: D:\\developpement
  entrant: ${dossier.parent}\\ocr\\input\\
  temporaire: ${dossier.parent}\\temp
  tesseract: ${dossier.parent}\\ocr\\config\\tessdata
  traitement1: t1
  traitement2: t2
liste:
  fleurs:
    - Phacélie
    - Aigremoine eupatoire
    - Germandrée
    - Tamaris
    - Seringat
    - Tilleul
    - Nerprun
    - Sedum
    - Sumac
    - Phaoélie
    - Erable
    - Noyer
    - Phacélie
    - Colza
    - Marronnier
    - Ronce
    - Luzerne
    - Mélilot
    - Pin
    - Colz
    - Myosotis
    - Sainfoin
    - Lotier
    - Saule
    - Graminé
    - Graminées
    - Fruitiers
    - Trèfle blanc
    - Erable
    - Papaver
    - Noyer
    - Réséda
    - Cornouiller sanguin
    - Pyracanthe
    - Cercis
    - Thym