CREATE USER usrocr WITH
	LOGIN
	NOSUPERUSER
	CREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'pwdocr';

CREATE DATABASE ocr
    WITH
    OWNER = usrocr
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;

GRANT USAGE ON SCHEMA public TO usrocr;