-- #######################################################################################################
-- INSERTION TABLE : param_matrice
-- #######################################################################################################

INSERT INTO param_matrice (nom, identifiant) VALUES('Pollen', 'P');
INSERT INTO param_matrice (nom, identifiant) VALUES('Miel', 'M');




-- #######################################################################################################
-- INSERTION TABLE : param_contact
-- #######################################################################################################

INSERT INTO param_contact (nom, prenom, site, departement, region, telephone, correspondance) VALUES('Julien','Delaunay','St-aubin-la-plaine',85,'Vendée','',0);
INSERT INTO param_contact (nom, prenom, site, departement, region, telephone, correspondance) VALUES('David','Sowtys','Tavers',45,'Loiret','',1);
INSERT INTO param_contact (nom, prenom, site, departement, region, telephone, correspondance) VALUES('Eric','Lelong','Aspiran',34,'Hérault','', 2);
INSERT INTO param_contact (nom, prenom, site, departement, region, telephone, correspondance) VALUES('Pascal','Turani','Bourideys',33,'Gironde','',3);
INSERT INTO param_contact (nom, prenom, site, departement, region, telephone, correspondance) VALUES('Florent','Vacher','Tavers',45,'Loiret','',4);
INSERT INTO param_contact (nom, prenom, site, departement, region, telephone, correspondance) VALUES('Jean-François','Maréchal','Tilloy-Bellay',51,'Marne','',5);





-- #######################################################################################################
-- INSERTION TABLE : param_molecules_gms
-- #######################################################################################################

INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('1,4-dimethylnaphthalene',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('2-phenylphenol (ortho-) (A)',0.05);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('acetochlor (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('aclonifen (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('acrinathrine (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('alachlor (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('aldrin and dieldrin (aldrin and dieldrin combined expressed as dieldrin) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('aldrine (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('anthraquinone (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('benalaxyl including other mixtures of constituent isomers including benalaxyl-M (sum of isomers) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('benfluralin (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('benzoylprop-ethyl (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('bifenazate',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('bifénox (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('bifenthrine (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('biphenyl (A)',0.1);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('bromophos (bromophosmethyl) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('bromophos-ethyl (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('bromopropylate (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('butachlor (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('butafenacil (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('butralin (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('butylate (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('cadusafos (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('captan',0.02);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('captan (Sum of captan and THPI, expressed as captan)',0.02);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('carbophenothion (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('chinomethionate (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('chlorbufam (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('chlordane (sum of cis- and trans-chlordane) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('chlorfénapyr (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('chlorfenson (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('chlorméphos (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('chlorobenside (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('chlorobenzilate (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('chloroneb (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('chlorothalonil',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('chlorpropham (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('chlorpyriphos-éthyl (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('chlorpyriphos-méthyl (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('chlorthal-dimethyl (DCPA) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('chlozolinate (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('coumaphos (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('crimidine (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('cyanophenphos (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('cycloate (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('cyflufenamid: sum of cyflufenamid (Z-isomer) and its E-isomer (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('cyfluthrin (cyfluthrin including other mixtures of constituent isomers (sum of isomers)) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('cyhalofop-butyl (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('cyhalothrin (sum of gamma and lambda) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('cypermethrin (cypermethrin including other mixtures of constituent isomers (sum of isomers)) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('DBCP',0.1);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('DDD (o,p''-)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('DDD(p,p''-) = TDE',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('DDE (op'')',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('DDE (p,p'')',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('DDT (op''-)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('DDT (pp'')',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('DDT (sum of p,p´-DDT, o,p´-DDT, p-p´-DDE and p,p´-TDE (DDD) expressed as DDT) (F)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('DEET (N,N-diethyl-Mtoluamide) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('deltamethrin (cisdeltamethrin) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('desmetryne (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('diazinon (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('dichlobenil (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('dichlofenthion (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('dichlofluanide',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('dichlormide (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('dichlorvos (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('diclofop-methyl',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('diclofop-methyl (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('dicloran (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('dicofol (o,p'')',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('dicofol (p,p'')',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('dicofol (sum of p, p´ and o,p´ isomers)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('dieldrin (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('diméthachlore (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('diphenamid (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('diphenylamine (A)',0.05);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('ditalimfos (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('DMST (A)',0.02);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('endosulfan (alfa-) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('endosulfan (beta-) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('endosulfan (sulphate-) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('endosulfan (sum of alpha- and beta-isomers and endosulfan-sulphate expresses as endosulfan) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('endrine (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('EPN (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('EPTC (ethyl dipropylthiocarbamate) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('esfenvalerate (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('ethalfluralin (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('ethion (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('ethofumesate (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('ethofumesate (sum of ethofumesate and the metabolite 2,3-dihydro-3,3-dimethyl-2-oxobenzofuran-5-yl methane sulphonate expressed as ethofumesate) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('ethofumesate-2-keto (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('ethoprophos (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('etofenprox (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('etridiazole',0.05);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('etrimfos (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('famoxadone (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('fenchlorphos (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('fenchlorphos',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('fenchlorphos-oxon',0.02);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('fenitrothion (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('fenpropathrine (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('fenpropimorphe (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('fenson (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('fenvalerate (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('fenvalerate (sum of SS,RR,SR and RS) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('fipronil (A)',0.005);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('fipronil (sum fipronil + sulfone metabolite (MB46136) expressed as fipronil) (A)',0.005);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('fipronil-desulfinyl (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('fipronil-sulfone (A)',0.005);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('flucythrinate (flucythrinate including other mixtures of constituent isomers (sum of isomers)) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('fludioxonil (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('flumetralin (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('formothion (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('hch (alfa-) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('hch (beta-) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('HCH (delta-) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('HCH (epsilon-) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('heptachlor (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('heptachlor (sum of heptachlor and heptachlor epoxide expressed as heptachlor) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('heptachlor epoxyde (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('heptenophos (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('hexachlorobenzene (HCB) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('hexachlorociclohexane (HCH), sum of isomers, except the gamma isomer (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('iodofenfos (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('ipconazole',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('isocarbofos (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('isofenphos (-ethyl) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('isofenphos-methyl (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('isoprocarb (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('isopropalin (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('lindane (Gamma-isomer of hexachlorocyclohexane (HCH)) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('malaoxon (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('malathion (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('malathion (sum of malathion and malaoxon expressed as malathion) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('mécarbam (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('mépronil (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('méthacrifos (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('méthidathion (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('methoprene (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('méthoxychlore (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('metrafenone (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('métribuzin',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('mevinphos (sum of E- and Z-isomers) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('mirex (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('nitrofène (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('nitrothale-isopropyl (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('oxadiargyl (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('oxadiazon (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('oxychlordane (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('oxyfluorfen (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('paraoxon-methyl',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('parathion (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('parathion-methyl (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('parathion-methyl (sum of parathion-methyl and paraoxon-methyl expressed as parathionmethyl)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('pebulate (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('pendimethalin (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('pentachloraniline (PCA) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('pentachloroanisol (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('penthiopyrade (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('permethrin (sum of isomers) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('phenothrin (phenothrin including other mixtures of constituent isomers (sum of isomers)) (A)',0.02);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('phorate (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('phosalone (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('phosmet',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('phosmet (phosmet and phosmet oxon expressed as phosmet)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('phosmet-oxon',0.05);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('pipéronyl-butoxyde (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('pirimiphos-éthyl (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('pirimiphos-méthyl (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('pretilachlor (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('procymidone (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('profluralin (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('prométryne (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('propargite (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('prothiofos (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('pyrazophos (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('pyridabène (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('pyriproxyfène (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('quinalphos (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('quintozene (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('quintozene (sum of quintozene and pentachloro-aniline expressed as quintozene) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('silafluofen (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('silthiofam (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('spirodiclofen (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('spiromesifen (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('sulfotep (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('sulprofos (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('tau-fluvalinate (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('tecnazene (TCNB) (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('téfluthrine (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('terbacil (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('terbuthylazine (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('terbutryne (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('tetrachlorvinphos (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('tétradifon (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('tetrahydrophtalimide',0.02);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('tiocarbazil (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('tolclofos-méthyl (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('tolfenpyrad (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('tolylfluanid (sum of tolylfluanid and dimethylaminosulfotoluidi de expressed as tolylfluanid) (R)',0.02);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('tolylfluanide',0.02);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('transfluthrin (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('tri-allate (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('trifluralin (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('vinclozolin (A)',0.01);
INSERT INTO param_molecules_gms (nom, valeurTrace) VALUES ('vinclozolin - TOTAL (A)',0.01);




-- #######################################################################################################
-- INSERTION TABLE : param_molecules_lms
-- #######################################################################################################

INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('2-(1-naphtyl)acetamide (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('6-benzyladenine (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('abamectine (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('acephate (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('acetamiprid (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('acibenzolar- S- methyl (sum of acibenzolar- S- methyl and acibenzolar acid (free and conjugated), expressed as acibenzolar- S- methyl)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('acibenzolar-acid',0.05);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('acibenzolar-S-methyl (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('aldicarb (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('aldicarb - sulfon (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('aldicarb - sulfoxide (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('aldicarb (sum of aldicarb, its sulfoxide and its sulfone, expressed as aldicarb) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('allethrin (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('ametoctradin (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('amétryne (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('amidosulfuron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('amisulbrom (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('asulame (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('atrazine (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('azadirachtin (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('azamethiphos (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('azimsulfuron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('azinphos-ethyl (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('azinphos-methyl (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('azoxystrobine (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('beflubutamid (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('bendiocarb (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('bensulfuron-methyl (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('benthiavalicarb (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('bispyribac-sodium (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('bitertanol (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('bixafen (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('boscalid (A)',0.02);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('bromacil (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('bromuconazole (sum of diasteroisomers) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('bupirimate (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('buprofézine (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('carbaryl (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('carbendazim and benomyl (sum of benomyl and carbendazim expressed as carbendazim) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('carbétamide (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('carbofuran (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('carbofuran (3-OH-) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('carbofuran (sum of carbofuran (including any carbofuran generated from carbosulfan, benfuracarb or furathiocarb) and 3-OH carbofuran expressed as carb (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('carbosulfan (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('carboxin (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('carfentrazone-ethyl (determined as carfentrazone and expressed as carfentrazone-ethyl) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('chlorantraniliprole (DPX E-2Y45) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('chlorbromuron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('chlorfenvinphos (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('chlorfluazuron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('chloridazon (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('chlorotoluron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('chloroxuron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('chlorsulfuron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('cinerin I',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('cinerin II',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('clethodim (sum of sethoxydim and clethodim including degradation products calculated as sethoxydim) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('cléthodime (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('clodinafop (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('clodinafop and its Sisomers and their salts, expressed as clodinafop (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('clodinafop-propargyl (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('clofentezine (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('clomazone (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('clothianidin (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('cyantraniliprole (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('cyazofamid (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('cycloxidime (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('cyflumetofen (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('cymiazole (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('cymoxanil (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('cyproconazole (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('cyprodinyl (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('dazomet (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('demethon-s-methyl (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('demeton-S-methyl-sulfon (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('diafenthiuron',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('dicrotophos (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('diéthofencarb (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('difénoconazole (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('diflubenzuron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('diflufénicanil (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('dimefox (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('Dimethenamid including other mixtures of constituent isomers including dimethenamidP (sum of isomers) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('dimethoate (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('dimethoate (sum of dimethoate and omethoate expressed as dimethoate) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('dimethomorph (sum of isomers) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('dimoxystrobin (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('diniconazole (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('dinotefuran (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('disulfoton (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('disulfoton (sum of disulfoton, disulfoton sulfoxide and disulfoton sulfone expressed as disulfoton) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('disulfoton-sulfone (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('disulfoton-sulfoxide (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('diuron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('dodemorph (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('dodine (A)',0.02);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('emamectin benzoate B1a (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('emamectin benzoate B1a, expressed as emamectin (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('emamectin benzoate B1b (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('epoxiconazole (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('ethametsulfuron-methyl (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('ethiofencarb (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('ethirimol (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('ethoxysulfuron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('etoxazole (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fénamidone (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fenamiphos (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fenamiphos - sulfone (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fenamiphos - sulfoxide (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fenamiphos (sum of fenamiphos and its sulphoxide and sulphone expressed as fenamiphos) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fénarimol (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fénazaquin (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fenbuconazole (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fenhexamid (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fenobucarb (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fenoxaprop-P (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fenoxaprop-P-éthyl (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fénoxycarb (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fenpiclonil (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fenpropidin (sum of fenpropidin and its salts, expressed as fenpropidin) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fenpyrazamine (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fenpyroximate (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fensulfothion (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fensulfothion-oxon (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fensulfothion-oxon-sulfon (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fensulfothion-sulfon (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fenthion (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fenthion - sulfon (A)',0.05);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fenthion - sulfoxide (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('Fenthion (fenthion and its oxigen analogue, their sulfoxides and sulfone expressed as parent) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fenthion-oxon (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fenthion-oxon-sulfone (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fenthion-oxon-sulfoxid (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fenuron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('flazasulfuron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('flonicamid (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('florasulam (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fluazifop-P (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fluazifop-P - butyl (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fluazifop-P-butyl (fluazifop acid (free )) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fluazinam (A)',0.02);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('flubendiamide (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('flufénacet (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('flufénoxuron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fluometuron',0.02);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fluopicolide (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fluopyram (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fluoxastrobin (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('flupyradifurone (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('flupyrsulfuron-méthyl (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fluquinconazole (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('flurochloridon (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fluroxypyr',0.02);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('flurtamone (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('flusilazole (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('flutolanil (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('flutriafol (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fluxapyroxad (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('FM-6 (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fonofos (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('foramsulfuron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('forchlorfenuron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fosthiazate (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('fuberidazole (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('furalaxyl (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('furathiocarbe (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('haloxyfop - R (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('haloxyfop including haloxyfop-R (HaloxyfopR methyl ester and haloxyfop-R expressed as haloxyfop-R) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('haloxyfop-methyl (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('hexaconazole (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('hexazinone (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('héxythiazox (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('imazalil (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('imazamox',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('imazapyr',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('imazaquine',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('imazosulfuron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('imidaclopride (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('indoxacarb (sum of indoxacarb and its R enantiomer) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('iodosulfuron-methyl (iodosulfuron-methyl including salts, expressed as iodosulfuron-methyl) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('iprobenfos (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('iprodione (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('iprovalicarbe (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('isoprothiolane (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('isoproturon (IPU) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('isopyrazam (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('isoxaben (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('krésoxim-méthyl (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('lenacil (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('linuron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('lufénuron (A)',0.02);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('mandipropamid (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('mépanipyrim (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('mesosulfuron-methyl (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('metaflumizone (sum of E- and Z- isomers) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('metalaxyl and metalaxylM (metalaxyl including other mixtures of constituent isomers including metalaxyl-M (sum of isomers)) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('métamitrone (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('metazachlor (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('metconazole (sum of isomers) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('méthabenzthiazuron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('méthamidophos (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('methiocarb (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('methiocarb (sum of methiocarb and methiocarb sulfoxide and sulfone, expressed as methiocarb) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('methiocarb-sulfon (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('methiocarb-sulfoxide (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('metholachlor and metholachlor-S (metholachlor including other mixtures of constituent isomers including S-metholachlor (sum of isomers)) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('methomyl (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('méthoxyfenozide (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('metobromuron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('métosulame (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('métoxuron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('metsulfuron-méthyl (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('molinate (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('monocrotophos (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('monolinuron (A)',0.02);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('myclobutanil (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('napropamide (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('nicosulfuron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('nitenpyram (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('novaluron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('nuarimol (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('ofurace (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('omethoate (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('oxadixyl (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('oxamyl (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('oxycarboxin (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('oxydemeton-methyl (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('oxydemeton-methyl (sum of oxydemeton-methyl and demeton-Smethylsulfone expressed as oxydemeton-methyl) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('paclobutrazol (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('penconazole (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('pencycuron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('penoxsulam (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('pethoxamid (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('phenmedipham (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('phenthoate (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('phosphamidon (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('phoxim (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('picolinafène (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('picoxystrobin (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('pinoxaden (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('pirimicarb (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('prochloraze (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('profenofos (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('promecarb (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('propamocarb (sum of propamocarb and its salt expressed as propamocarb) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('propanil (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('propaquizafop (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('propazin (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('propham (IPC) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('propiconazole (sum of isomers) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('propoxur (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('propyzamide (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('proquinazid (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('prosulfocarbe (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('prosulfuron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('prothioconazole: prothioconazole-dethio (sum of isomers) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('pymétrozine (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('pyraclostrobine (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('pyraflufen-éthyl (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('pyrethrin I',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('pyrethrin II',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('pyrethrins',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('pyridafol',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('pyridalyl (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('pyridaphenthion (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('pyridate',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('Pyridate (sum of pyridate, its hydrolysis product CL 9673 (6-chloro-4hydroxy-3phenylpyridazin) and hydrolysable conjugates of CL 9673 expressed as p',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('pyrifénox (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('pyriméthanil (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('pyriofenone (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('quinclorac (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('quinmérac',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('quinoxyfène (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('quizalofop, incl. quizalofop-P (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('quizalofop-éthyl (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('rimsulfuron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('roténone (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('séthoxydime (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('simazine (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('spinetoram (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('spinetoram I (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('spinetoram II (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('spinosad: sum of spinosyn A and spinosyn D, expressed as spinosad (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('spinosyn A (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('spinosyn D (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('spirotetramat (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('spirotetramat and its 4 metabolites BYI08330enol, BYI08330ketohydroxy, BYI08330monohydroxy, and BYI08330 enol-glucoside, expressed as spirotetramat (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('spirotetramat-enol (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('spirotetramat-enolglucoside (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('spirotetramat-keto-hydrox (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('spirotetramat-monohydrox (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('spiroxamine (sum of isomers) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('sulfosulfuron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('sulfoxaflor (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('tebuconazole (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('tébufenozide (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('tébufenpyrad (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('tepraloxydim (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('terbufos (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('terbufos-sulfon (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('terbufos-sulfoxide (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('tétraconazole (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('tetramethrine (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('thiabendazole (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('thiacloprid (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('thiametoxam (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('thifensulfuron-méthyle (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('thiobencarb (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('thiodicarb (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('thionazine (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('thiophanate-methyl (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('triadimefon and triadimenol (sum of triadimefon and triadimenol) (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('triadiméfone (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('triadimenol (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('triasulfuron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('triazophos (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('trichlorfon (A)',0.02);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('tricyclazole (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('tridemorphe (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('trifloxystrobin (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('triflumizole (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('triflumuron (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('triforine (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('trinexapac (sum of trinexapac (acid) and its salts, expressed as trinexapac) (A)',0.02);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('triticonazole (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('valifenalate (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('vamidothion (A)',0.01);
INSERT INTO param_molecules_lms (nom, valeurTrace) VALUES ('zoxamide (A)',0.01);




-- #######################################################################################################
-- INSERTION TABLE : param_type
-- #######################################################################################################

INSERT INTO param_type (valeur) VALUES ('DOMINANT');
INSERT INTO param_type (valeur) VALUES ('ACCOMPAGNEMENT');
INSERT INTO param_type (valeur) VALUES ('ISOLE');




-- #######################################################################################################
-- INSERTION TABLE : param_famille
-- #######################################################################################################

INSERT INTO param_famille(nom) VALUES ('Amaranthaceae');
INSERT INTO param_famille(nom) VALUES ('Anacardiaceae');
INSERT INTO param_famille(nom) VALUES ('Apiaceae');
INSERT INTO param_famille(nom) VALUES ('Araliaceae');
INSERT INTO param_famille(nom) VALUES ('Arecaceae');
INSERT INTO param_famille(nom) VALUES ('Asteraceae');
INSERT INTO param_famille(nom) VALUES ('Betulaceae');
INSERT INTO param_famille(nom) VALUES ('Boraginaceae');
INSERT INTO param_famille(nom) VALUES ('Brassicaceae');
INSERT INTO param_famille(nom) VALUES ('Buddlejaceae');
INSERT INTO param_famille(nom) VALUES ('Campanulaceae');
INSERT INTO param_famille(nom) VALUES ('Caprifoliaceae');
INSERT INTO param_famille(nom) VALUES ('Caryophilaceae');
INSERT INTO param_famille(nom) VALUES ('Cistaceae');
INSERT INTO param_famille(nom) VALUES ('Convolvulaceae');
INSERT INTO param_famille(nom) VALUES ('Cornaceae');
INSERT INTO param_famille(nom) VALUES ('Crassulaceae');
INSERT INTO param_famille(nom) VALUES ('Cyperaceae');
INSERT INTO param_famille(nom) VALUES ('Dipsacaceae');
INSERT INTO param_famille(nom) VALUES ('Ericaceae');
INSERT INTO param_famille(nom) VALUES ('Euphorbiaceae');
INSERT INTO param_famille(nom) VALUES ('Fabaceae');
INSERT INTO param_famille(nom) VALUES ('Fagaceae');
INSERT INTO param_famille(nom) VALUES ('Fleurs');
INSERT INTO param_famille(nom) VALUES ('Hippocastanaceae');
INSERT INTO param_famille(nom) VALUES ('Hydrangeaceae');
INSERT INTO param_famille(nom) VALUES ('Hydrophyllaceae');
INSERT INTO param_famille(nom) VALUES ('Hyperaceae');
INSERT INTO param_famille(nom) VALUES ('Lamiaceae');
INSERT INTO param_famille(nom) VALUES ('Liliaceae');
INSERT INTO param_famille(nom) VALUES ('Lythraceae');
INSERT INTO param_famille(nom) VALUES ('Magnoliaceae');
INSERT INTO param_famille(nom) VALUES ('Maloideae');
INSERT INTO param_famille(nom) VALUES ('Oleaceae');
INSERT INTO param_famille(nom) VALUES ('Papaveraceae');
INSERT INTO param_famille(nom) VALUES ('Plantaginaceae');
INSERT INTO param_famille(nom) VALUES ('Poaceae');
INSERT INTO param_famille(nom) VALUES ('Polygonaceae');
INSERT INTO param_famille(nom) VALUES ('Portulacaceae');
INSERT INTO param_famille(nom) VALUES ('Ranunculaceae');
INSERT INTO param_famille(nom) VALUES ('Resedaceae');
INSERT INTO param_famille(nom) VALUES ('Rhamnaceae');
INSERT INTO param_famille(nom) VALUES ('Rosaceae');
INSERT INTO param_famille(nom) VALUES ('Salicaceae');
INSERT INTO param_famille(nom) VALUES ('Sapindaceae');
INSERT INTO param_famille(nom) VALUES ('Solenaceae');
INSERT INTO param_famille(nom) VALUES ('Vitaceae');




-- #######################################################################################################
-- INSERTION TABLE : param_espece
-- #######################################################################################################

INSERT INTO param_espece(famille_id,nom) VALUES (3,' ');
INSERT INTO param_espece(famille_id,nom) VALUES (45,'Acer');
INSERT INTO param_espece(famille_id,nom) VALUES (25,'Aesculus');
INSERT INTO param_espece(famille_id,nom) VALUES (6,'Ambrosia');
INSERT INTO param_espece(famille_id,nom) VALUES (6,'Artemisia');
INSERT INTO param_espece(famille_id,nom) VALUES (6,'Aster');
INSERT INTO param_espece(famille_id,nom) VALUES (22,'Bituminaria');
INSERT INTO param_espece(famille_id,nom) VALUES (9,'Brassica');
INSERT INTO param_espece(famille_id,nom) VALUES (10,'Buddleia');
INSERT INTO param_espece(famille_id,nom) VALUES (20,'Calluna');
INSERT INTO param_espece(famille_id,nom) VALUES (15,'Calystegia');
INSERT INTO param_espece(famille_id,nom) VALUES (7,'Carpinus');
INSERT INTO param_espece(famille_id,nom) VALUES (23,'Castanea');
INSERT INTO param_espece(famille_id,nom) VALUES (6,'Centaurea');
INSERT INTO param_espece(famille_id,nom) VALUES (5,'Chamaerops');
INSERT INTO param_espece(famille_id,nom) VALUES (1,'Chenopodium');
INSERT INTO param_espece(famille_id,nom) VALUES (6,'Cicorium');
INSERT INTO param_espece(famille_id,nom) VALUES (14,'Cistus');
INSERT INTO param_espece(famille_id,nom) VALUES (40,'Clematis');
INSERT INTO param_espece(famille_id,nom) VALUES (16,'Cornus');
INSERT INTO param_espece(famille_id,nom) VALUES (43,'Crataegus');
INSERT INTO param_espece(famille_id,nom) VALUES (46,'Datura');
INSERT INTO param_espece(famille_id,nom) VALUES (8,'Echium');
INSERT INTO param_espece(famille_id,nom) VALUES (20,'Erica');
INSERT INTO param_espece(famille_id,nom) VALUES (6,'Eupatorium');
INSERT INTO param_espece(famille_id,nom) VALUES (38,'Fagopyrum');
INSERT INTO param_espece(famille_id,nom) VALUES (23,'Fagus');
INSERT INTO param_espece(famille_id,nom) VALUES (42,'Frangula');
INSERT INTO param_espece(famille_id,nom) VALUES (34,'Fraxinus');
INSERT INTO param_espece(famille_id,nom) VALUES (4,'Hedera');
INSERT INTO param_espece(famille_id,nom) VALUES (6,'Helianthus');
INSERT INTO param_espece(famille_id,nom) VALUES (3,'Heracleum');
INSERT INTO param_espece(famille_id,nom) VALUES (6,'Hieracium');
INSERT INTO param_espece(famille_id,nom) VALUES (28,'Hypericum');
INSERT INTO param_espece(famille_id,nom) VALUES (11,'Jasione');
INSERT INTO param_espece(famille_id,nom) VALUES (34,'Ligustrum');
INSERT INTO param_espece(famille_id,nom) VALUES (32,'Liriodendron');
INSERT INTO param_espece(famille_id,nom) VALUES (31,'Lythrum');
INSERT INTO param_espece(famille_id,nom) VALUES (6,'Matricaria');
INSERT INTO param_espece(famille_id,nom) VALUES (22,'Melilotus');
INSERT INTO param_espece(famille_id,nom) VALUES (21,'Mercurialis');
INSERT INTO param_espece(famille_id,nom) VALUES (40,'Nigella');
INSERT INTO param_espece(famille_id,nom) VALUES (22,'Onobrychis');
INSERT INTO param_espece(famille_id,nom) VALUES (29,'Origanum');
INSERT INTO param_espece(famille_id,nom) VALUES (35,'Papaver');
INSERT INTO param_espece(famille_id,nom) VALUES (38,'Persicaria');
INSERT INTO param_espece(famille_id,nom) VALUES (27,'Phacelia');
INSERT INTO param_espece(famille_id,nom) VALUES (26,'Phyladelphus');
INSERT INTO param_espece(famille_id,nom) VALUES (2,'Pistacia');
INSERT INTO param_espece(famille_id,nom) VALUES (36,'Plantago');
INSERT INTO param_espece(famille_id,nom) VALUES (39,'Portulaca');
INSERT INTO param_espece(famille_id,nom) VALUES (33,'Pyracantha');
INSERT INTO param_espece(famille_id,nom) VALUES (23,'Quercus');
INSERT INTO param_espece(famille_id,nom) VALUES (42,'Rahmus');
INSERT INTO param_espece(famille_id,nom) VALUES (40,'Ranunculus');
INSERT INTO param_espece(famille_id,nom) VALUES (41,'Reseda');
INSERT INTO param_espece(famille_id,nom) VALUES (2,'Rhus');
INSERT INTO param_espece(famille_id,nom) VALUES (22,'Robinia');
INSERT INTO param_espece(famille_id,nom) VALUES (43,'Rubus');
INSERT INTO param_espece(famille_id,nom) VALUES (38,'Rumex');
INSERT INTO param_espece(famille_id,nom) VALUES (44,'Salix');
INSERT INTO param_espece(famille_id,nom) VALUES (12,'Sambucus');
INSERT INTO param_espece(famille_id,nom) VALUES (17,'Sedum');
INSERT INTO param_espece(famille_id,nom) VALUES (6,'Senecio');
INSERT INTO param_espece(famille_id,nom) VALUES (46,'Solanum');
INSERT INTO param_espece(famille_id,nom) VALUES (6,'Tarraxacum');
INSERT INTO param_espece(famille_id,nom) VALUES (22,'Trifolium');
INSERT INTO param_espece(famille_id,nom) VALUES (22,'Vicia');
INSERT INTO param_espece(famille_id,nom) VALUES (47,'Vitis');
INSERT INTO param_espece(famille_id,nom) VALUES (37,'Zea');




-- #######################################################################################################
-- INSERTION TABLE : param_fleurs
-- #######################################################################################################

INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (16,'Chénopode','Chénopode');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (49,'Terebinthus','Terebinthus');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (57,'Rhus spp.','Rhus spp.');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (1,'Apiaceae','Apiaceae');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (1,'Ombellifère','Ombellifère');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (32,'Berce','Berce');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (30,'Lierre','Lierre');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (15,'Chamaerops humilis','Chamaerops');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (15,'Chamaerops','Chamaerops');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (66,'Pissenlit','Pissenlit');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (39,'Matricaire','Matricaire');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (1,'Chardon','Chardon');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (64,'Seneçon','Seneçon');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (31,'Tournesol','Tournesol');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (1,'Pâquerette','Pâquerette');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (17,'Chicorée','Chicorée');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (33,'Epervière','Epervière');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (25,'Eupatoire','Eupatoire');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (6,'Aster','Aster');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (14,'Centaurée','Centaurée');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (1,'Asteraceae','Asteraceae');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (4,'Ambroisie','Ambroisie');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (5,'Armoise','Armoise');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (12,'Betulaceae','Betulaceae');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (23,'Vipérine','Vipérine');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (8,'Colza','Colza');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (8,'Crucifères','Brassicaceae');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (8,'Moutarde','Moutarde');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (8,'Brassicaceae','Brassicaceae');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (9,'Buddléia','Buddléia');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (35,'Jasione','Jasione');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (62,'Sureau','Sureau');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (1,'Caryophilaceae','Caryophilaceae');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (18,'Cistes','Cistes');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (18,'Cistaceae','Cistes');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (11,'Liseron','Liseron');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (20,'Cornouiller','Cornouiller');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (63,'Sédum','Sédum');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (1,'Carex','Carex');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (1,'Knautie','Knautie');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (24,'Bruyère cendrée','Bruyère cendrée');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (10,'Callune','Callune');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (41,'Mercuriale','Mercuriale');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (1,'Gléditschia','Gléditschia');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (43,'Sainfoin','Sainfoin');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (67,'Trefle des pres','Trèfle des prés');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (68,'Fève','Fève');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (67,'Trèfle blanc','Trèfle blanc');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (58,'Acacia','Acacia');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (7,'Psoralée','Psoralée');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (40,'Mélilot','Mélilot');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (1,'Genêt','Genêt');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (53,'Chêne','Chêne');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (27,'Hêtre','Hêtre');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (53,'Quercus','Chêne');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (13,'Chataignier','Châtaignier');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (1,'Fleurs','Fleurs');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (3,'Marronnier','Marronnier');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (48,'Seringat','Seringat');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (47,'Phacélie','Phacélie');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (34,'Millepertuis','Millepertuis');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (44,'Marjolaine','Marjolaine');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (1,'Liliacée','Liliacée');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (38,'Salicaire','Salicaire');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (37,'Tulipier de virginie','Tulipier de virginie');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (52,'Pyracantha','Pyracantha');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (29,'Frêne','Frêne');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (36,'Troène','Troène');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (45,'Papaver spp.','Papaver spp.');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (50,'Plantain','Plantain');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (1,'Poaceae','Poaceae');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (70,'Maïs','Maïs');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (60,'Oseille','Oseille');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (26,'Sarrasin','Sarrasin');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (46,'Persicaire','Persicaire');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (51,'Portulaca spp.','Portulaca spp.');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (19,'Clématite','Clématite');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (55,'Ranunculaceae','Ranunculaceae');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (42,'Nigelle','Nigelle');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (56,'Reseda','Reseda');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (54,'Nerprun','Nerprun');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (28,'Bourdaine','Bourdaine');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (1,'Fruitiers','Fruitiers');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (21,'Aubépine','Aubépine');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (1,'Rosaceae','Rosaceae');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (59,'Ronce','Ronce');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (61,'Saules','saules');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (2,'Erable','Erable');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (65,'Solenaceae','Solenaceae');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (65,'Morelle','Morelle');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (22,'Datura','Datura');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (69,'Vigne','Vigne');
INSERT INTO param_fleurs(espece_id,nom, nom2) VALUES (1,'Vigne vierge','Vigne vierge');
