-- #######################################################################################################
-- INSERTION TABLE : param_genre
-- #######################################################################################################

INSERT INTO param_genre(famille_id,nom) VALUES (3,' ');
INSERT INTO param_genre(famille_id,nom) VALUES (45,'Acer');
INSERT INTO param_genre(famille_id,nom) VALUES (25,'Aesculus');
INSERT INTO param_genre(famille_id,nom) VALUES (6,'Ambrosia');
INSERT INTO param_genre(famille_id,nom) VALUES (6,'Artemisia');
INSERT INTO param_genre(famille_id,nom) VALUES (6,'Aster');
INSERT INTO param_genre(famille_id,nom) VALUES (22,'Bituminaria');
INSERT INTO param_genre(famille_id,nom) VALUES (9,'Brassica');
INSERT INTO param_genre(famille_id,nom) VALUES (10,'Buddleia');
INSERT INTO param_genre(famille_id,nom) VALUES (20,'Calluna');
INSERT INTO param_genre(famille_id,nom) VALUES (15,'Calystegia');
INSERT INTO param_genre(famille_id,nom) VALUES (7,'Carpinus');
INSERT INTO param_genre(famille_id,nom) VALUES (23,'Castanea');
INSERT INTO param_genre(famille_id,nom) VALUES (6,'Centaurea');
INSERT INTO param_genre(famille_id,nom) VALUES (5,'Chamaerops');
INSERT INTO param_genre(famille_id,nom) VALUES (1,'Chenopodium');
INSERT INTO param_genre(famille_id,nom) VALUES (6,'Cicorium');
INSERT INTO param_genre(famille_id,nom) VALUES (14,'Cistus');
INSERT INTO param_genre(famille_id,nom) VALUES (40,'Clematis');
INSERT INTO param_genre(famille_id,nom) VALUES (16,'Cornus');
INSERT INTO param_genre(famille_id,nom) VALUES (43,'Crataegus');
INSERT INTO param_genre(famille_id,nom) VALUES (46,'Datura');
INSERT INTO param_genre(famille_id,nom) VALUES (8,'Echium');
INSERT INTO param_genre(famille_id,nom) VALUES (20,'Erica');
INSERT INTO param_genre(famille_id,nom) VALUES (6,'Eupatorium');
INSERT INTO param_genre(famille_id,nom) VALUES (38,'Fagopyrum');
INSERT INTO param_genre(famille_id,nom) VALUES (23,'Fagus');
INSERT INTO param_genre(famille_id,nom) VALUES (42,'Frangula');
INSERT INTO param_genre(famille_id,nom) VALUES (34,'Fraxinus');
INSERT INTO param_genre(famille_id,nom) VALUES (4,'Hedera');
INSERT INTO param_genre(famille_id,nom) VALUES (6,'Helianthus');
INSERT INTO param_genre(famille_id,nom) VALUES (3,'Heracleum');
INSERT INTO param_genre(famille_id,nom) VALUES (6,'Hieracium');
INSERT INTO param_genre(famille_id,nom) VALUES (28,'Hypericum');
INSERT INTO param_genre(famille_id,nom) VALUES (11,'Jasione');
INSERT INTO param_genre(famille_id,nom) VALUES (34,'Ligustrum');
INSERT INTO param_genre(famille_id,nom) VALUES (32,'Liriodendron');
INSERT INTO param_genre(famille_id,nom) VALUES (31,'Lythrum');
INSERT INTO param_genre(famille_id,nom) VALUES (6,'Matricaria');
INSERT INTO param_genre(famille_id,nom) VALUES (22,'Melilotus');
INSERT INTO param_genre(famille_id,nom) VALUES (21,'Mercurialis');
INSERT INTO param_genre(famille_id,nom) VALUES (40,'Nigella');
INSERT INTO param_genre(famille_id,nom) VALUES (22,'Onobrychis');
INSERT INTO param_genre(famille_id,nom) VALUES (29,'Origanum');
INSERT INTO param_genre(famille_id,nom) VALUES (35,'Papaver');
INSERT INTO param_genre(famille_id,nom) VALUES (38,'Persicaria');
INSERT INTO param_genre(famille_id,nom) VALUES (27,'Phacelia');
INSERT INTO param_genre(famille_id,nom) VALUES (26,'Phyladelphus');
INSERT INTO param_genre(famille_id,nom) VALUES (2,'Pistacia');
INSERT INTO param_genre(famille_id,nom) VALUES (36,'Plantago');
INSERT INTO param_genre(famille_id,nom) VALUES (39,'Portulaca');
INSERT INTO param_genre(famille_id,nom) VALUES (33,'Pyracantha');
INSERT INTO param_genre(famille_id,nom) VALUES (23,'Quercus');
INSERT INTO param_genre(famille_id,nom) VALUES (42,'Rahmus');
INSERT INTO param_genre(famille_id,nom) VALUES (40,'Ranunculus');
INSERT INTO param_genre(famille_id,nom) VALUES (41,'Reseda');
INSERT INTO param_genre(famille_id,nom) VALUES (2,'Rhus');
INSERT INTO param_genre(famille_id,nom) VALUES (22,'Robinia');
INSERT INTO param_genre(famille_id,nom) VALUES (43,'Rubus');
INSERT INTO param_genre(famille_id,nom) VALUES (38,'Rumex');
INSERT INTO param_genre(famille_id,nom) VALUES (44,'Salix');
INSERT INTO param_genre(famille_id,nom) VALUES (12,'Sambucus');
INSERT INTO param_genre(famille_id,nom) VALUES (17,'Sedum');
INSERT INTO param_genre(famille_id,nom) VALUES (6,'Senecio');
INSERT INTO param_genre(famille_id,nom) VALUES (46,'Solanum');
INSERT INTO param_genre(famille_id,nom) VALUES (6,'Tarraxacum');
INSERT INTO param_genre(famille_id,nom) VALUES (22,'Trifolium');
INSERT INTO param_genre(famille_id,nom) VALUES (22,'Vicia');
INSERT INTO param_genre(famille_id,nom) VALUES (47,'Vitis');
INSERT INTO param_genre(famille_id,nom) VALUES (37,'Zea');


commit;