SET client_encoding = 'UTF8';
-- #######################################################################################################
-- INSERTION TABLE : param_molecules_gms
-- #######################################################################################################

INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('1,4-dimethylnaphthalene', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('2-phenylphenol (ortho-) (A)', 1, 0.05);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('acetochlor (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('aclonifen (A)', 2, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('acrinathrine (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('alachlor (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('aldrin and dieldrin (aldrin and dieldrin combined expressed as dieldrin) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('aldrine (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('anthraquinone (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('benalaxyl including other mixtures of constituent isomers including benalaxyl-M (sum of isomers) (A)', 3, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('benfluralin (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('benzoylprop-ethyl (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('bifenazate', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('bifénox (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('bifenthrine (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('biphenyl (A)', 1, 0.1);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('bromophos (bromophosmethyl) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('bromophos-ethyl (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('bromopropylate (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('butachlor (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('butafenacil (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('butralin (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('butylate (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('cadusafos (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('captan', 1, 0.02);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('captan (Sum of captan and THPI, expressed as captan)', 1, 0.02);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('carbophenothion (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('chinomethionate (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('chlorbufam (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('chlordane (sum of cis- and trans-chlordane) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('chlorfénapyr (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('chlorfenson (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('chlorméphos (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('chlorobenside (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('chlorobenzilate (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('chloroneb (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('chlorothalonil', 3, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('chlorpropham (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('chlorpyriphos-éthyl (A)', 4, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('chlorpyriphos-méthyl (A)', 4, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('chlorthal-dimethyl (DCPA) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('chlozolinate (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('coumaphos (A)', 5, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('crimidine (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('cyanophenphos (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('cycloate (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('cyflufenamid: sum of cyflufenamid (Z-isomer) and its E-isomer (A)', 3, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('cyfluthrin (cyfluthrin including other mixtures of constituent isomers (sum of isomers)) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('cyhalofop-butyl (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('cyhalothrin (sum of gamma and lambda) (A)', 4, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('cypermethrin (cypermethrin including other mixtures of constituent isomers (sum of isomers)) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('DBCP', 1, 0.1);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('DDD (o,p''-)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('DDD(p,p''-) = TDE', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('DDE (op'')', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('DDE (p,p'')', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('DDT (op''-)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('DDT (pp'')', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('DDT (sum of p,p´-DDT, o,p´-DDT, p-p´-DDE and p,p´-TDE (DDD) expressed as DDT) (F)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('DEET (N,N-diethyl-Mtoluamide) (A)', 7, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('deltamethrin (cisdeltamethrin) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('desmetryne (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('diazinon (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('dichlobenil (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('dichlofenthion (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('dichlofluanide', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('dichlormide (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('dichlorvos (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('diclofop-methyl', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('diclofop-methyl (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('dicloran (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('dicofol (o,p'')', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('dicofol (p,p'')', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('dicofol (sum of p, p´ and o,p´ isomers)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('dieldrin (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('diméthachlore (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('diphenamid (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('diphenylamine (A)', 1, 0.05);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('ditalimfos (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('DMST (A)', 1, 0.02);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('endosulfan (alfa-) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('endosulfan (beta-) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('endosulfan (sulphate-) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('endosulfan (sum of alpha- and beta-isomers and endosulfan-sulphate expresses as endosulfan) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('endrine (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('EPN (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('EPTC (ethyl dipropylthiocarbamate) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('esfenvalerate (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('ethalfluralin (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('ethion (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('ethofumesate (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('ethofumesate (sum of ethofumesate and the metabolite 2,3-dihydro-3,3-dimethyl-2-oxobenzofuran-5-yl methane sulphonate expressed as ethofumesate) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('ethofumesate-2-keto (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('ethoprophos (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('etofenprox (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('etridiazole', 1, 0.05);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('etrimfos (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('famoxadone (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('fenchlorphos (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('fenchlorphos', 1 ,0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('fenchlorphos-oxon', 1 ,0.02);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('fenitrothion (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('fenpropathrine (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('fenpropimorphe (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('fenson (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('fenvalerate (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('fenvalerate (sum of SS,RR,SR and RS) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('fipronil (A)', 1, 0.005);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('fipronil (sum fipronil + sulfone metabolite (MB46136) expressed as fipronil) (A)', 1, 0.005);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('fipronil-desulfinyl (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('fipronil-sulfone (A)', 1, 0.005);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('flucythrinate (flucythrinate including other mixtures of constituent isomers (sum of isomers)) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('fludioxonil (A)', 3, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('flumetralin (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('formothion (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('hch (alfa-) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('hch (beta-) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('HCH (delta-) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('HCH (epsilon-) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('heptachlor (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('heptachlor (sum of heptachlor and heptachlor epoxide expressed as heptachlor) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('heptachlor epoxyde (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('heptenophos (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('hexachlorobenzene (HCB) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('hexachlorociclohexane (HCH), sum of isomers, except the gamma isomer (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('iodofenfos (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('ipconazole', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('isocarbofos (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('isofenphos (-ethyl) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('isofenphos-methyl (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('isoprocarb (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('isopropalin (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('lindane (Gamma-isomer of hexachlorocyclohexane (HCH)) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('malaoxon (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('malathion (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('malathion (sum of malathion and malaoxon expressed as malathion) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('mécarbam (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('mépronil (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('méthacrifos (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('méthidathion (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('methoprene (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('méthoxychlore (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('metrafenone (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('métribuzin', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('mevinphos (sum of E- and Z-isomers) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('mirex (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('nitrofène (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('nitrothale-isopropyl (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('oxadiargyl (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('oxadiazon (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('oxychlordane (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('oxyfluorfen (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('paraoxon-methyl', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('parathion (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('parathion-methyl (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('parathion-methyl (sum of parathion-methyl and paraoxon-methyl expressed as parathionmethyl)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('pebulate (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('pendimethalin (A)', 2, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('pentachloraniline (PCA) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('pentachloroanisol (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('penthiopyrade (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('permethrin (sum of isomers) (A)', 4, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('phenothrin (phenothrin including other mixtures of constituent isomers (sum of isomers)) (A)', 1, 0.02);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('phorate (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('phosalone (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('phosmet', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('phosmet (phosmet and phosmet oxon expressed as phosmet)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('phosmet-oxon', 1, 0.05);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('pipéronyl-butoxyde (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('pirimiphos-éthyl (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('pirimiphos-méthyl (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('pretilachlor (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('procymidone (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('profluralin (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('prométryne (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('propargite (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('prothiofos (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('pyrazophos (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('pyridabène (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('pyriproxyfène (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('quinalphos (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('quintozene (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('quintozene (sum of quintozene and pentachloro-aniline expressed as quintozene) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('silafluofen (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('silthiofam (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('spirodiclofen (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('spiromesifen (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('sulfotep (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('sulprofos (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('tau-fluvalinate (A)', 4, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('tecnazene (TCNB) (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('téfluthrine (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('terbacil (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('terbuthylazine (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('terbutryne (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('tetrachlorvinphos (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('tétradifon (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('tetrahydrophtalimide', 1, 0.02);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('tiocarbazil (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('tolclofos-méthyl (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('tolfenpyrad (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('tolylfluanid (sum of tolylfluanid and dimethylaminosulfotoluidi de expressed as tolylfluanid) (R)', 1, 0.02);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('tolylfluanide', 1, 0.02);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('transfluthrin (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('tri-allate (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('trifluralin (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('vinclozolin (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('vinclozolin - TOTAL (A)', 1, 0.01);
INSERT INTO param_molecules_gms (nom, type_id, valeurTrace) VALUES ('RAS', 1, 0.00);




-- #######################################################################################################
-- INSERTION TABLE : param_molecules_lms
-- #######################################################################################################

INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('2-(1-naphtyl)acetamide (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('6-benzyladenine (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('abamectine (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('acephate (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('acetamiprid (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('acibenzolar- S- methyl (sum of acibenzolar- S- methyl and acibenzolar acid (free and conjugated), expressed as acibenzolar- S- methyl)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('acibenzolar-acid', 1, 0.05);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('acibenzolar-S-methyl (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('aldicarb (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('aldicarb - sulfon (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('aldicarb - sulfoxide (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('aldicarb (sum of aldicarb, its sulfoxide and its sulfone, expressed as aldicarb) (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('allethrin (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('ametoctradin (A)', 3, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('amétryne (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('amidosulfuron (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('amisulbrom (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('asulame (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('atrazine (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('azadirachtin (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('azamethiphos (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('azimsulfuron (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('azinphos-ethyl (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('azinphos-methyl (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('azoxystrobine (A)', 3, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('beflubutamid (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('bendiocarb (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('bensulfuron-methyl (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('benthiavalicarb (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('bispyribac-sodium (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('bitertanol (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('bixafen (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('boscalid (A)', 3, 0.02);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('bromacil (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('bromuconazole (sum of diasteroisomers) (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('bupirimate (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('buprofézine (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('carbaryl (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('carbendazim and benomyl (sum of benomyl and carbendazim expressed as carbendazim) (A)', 3, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('carbétamide (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('carbofuran (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('carbofuran (3-OH-) (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('carbofuran (sum of carbofuran (including any carbofuran generated from carbosulfan, benfuracarb or furathiocarb) and 3-OH carbofuran expressed as carb (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('carbosulfan (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('carboxin (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('carfentrazone-ethyl (determined as carfentrazone and expressed as carfentrazone-ethyl) (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('chlorantraniliprole (DPX E-2Y45) (A)', 4, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('chlorbromuron (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('chlorfenvinphos (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('chlorfluazuron (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('chloridazon (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('chlorotoluron (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('chloroxuron (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('chlorsulfuron (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('cinerin I',1 ,0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('cinerin II', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('clethodim (sum of sethoxydim and clethodim including degradation products calculated as sethoxydim) (A)', 2, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('cléthodime (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('clodinafop (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('clodinafop and its Sisomers and their salts, expressed as clodinafop (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('clodinafop-propargyl (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('clofentezine (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('clomazone (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('clothianidin (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('cyantraniliprole (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('cyazofamid (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('cycloxidime (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('cyflumetofen (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('cymiazole (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('cymoxanil (A)', 3, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('cyproconazole (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('cyprodinyl (A)', 3, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('dazomet (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('demethon-s-methyl (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('demeton-S-methyl-sulfon (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('diafenthiuron', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('dicrotophos (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('diéthofencarb (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('difénoconazole (A)', 3, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('diflubenzuron (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('diflufénicanil (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('dimefox (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('Dimethenamid including other mixtures of constituent isomers including dimethenamidP (sum of isomers) (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('dimethoate (A)', 4, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('dimethoate (sum of dimethoate and omethoate expressed as dimethoate) (A)', 4, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('dimethomorph (sum of isomers) (A)', 3, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('dimoxystrobin (A)', 3, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('diniconazole (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('dinotefuran (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('disulfoton (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('disulfoton (sum of disulfoton, disulfoton sulfoxide and disulfoton sulfone expressed as disulfoton) (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('disulfoton-sulfone (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('disulfoton-sulfoxide (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('diuron (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('dodemorph (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('dodine (A)', 1, 0.02);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('emamectin benzoate B1a (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('emamectin benzoate B1a, expressed as emamectin (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('emamectin benzoate B1b (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('epoxiconazole (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('ethametsulfuron-methyl (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('ethiofencarb (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('ethirimol (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('ethoxysulfuron (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('etoxazole (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fénamidone (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fenamiphos (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fenamiphos - sulfone (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fenamiphos - sulfoxide (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fenamiphos (sum of fenamiphos and its sulphoxide and sulphone expressed as fenamiphos) (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fénarimol (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fénazaquin (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fenbuconazole (A)', 3, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fenhexamid (A)', 3, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fenobucarb (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fenoxaprop-P (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fenoxaprop-P-éthyl (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fénoxycarb (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fenpiclonil (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fenpropidin (sum of fenpropidin and its salts, expressed as fenpropidin) (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fenpyrazamine (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fenpyroximate (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fensulfothion (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fensulfothion-oxon (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fensulfothion-oxon-sulfon (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fensulfothion-sulfon (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fenthion (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fenthion - sulfon (A)', 1, 0.05);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fenthion - sulfoxide (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('Fenthion (fenthion and its oxigen analogue, their sulfoxides and sulfone expressed as parent) (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fenthion-oxon (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fenthion-oxon-sulfone (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fenthion-oxon-sulfoxid (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fenuron (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('flazasulfuron (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('flonicamid (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('florasulam (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fluazifop-P (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fluazifop-P - butyl (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fluazifop-P-butyl (fluazifop acid (free )) (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fluazinam (A)', 1, 0.02);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('flubendiamide (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('flufénacet (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('flufénoxuron (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fluometuron', 1, 0.02);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fluopicolide (A)', 3, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fluopyram (A)', 3, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fluoxastrobin (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('flupyradifurone (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('flupyrsulfuron-méthyl (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fluquinconazole (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('flurochloridon (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fluroxypyr', 1, 0.02);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('flurtamone (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('flusilazole (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('flutolanil (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('flutriafol (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fluxapyroxad (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('FM-6 (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fonofos (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('foramsulfuron (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('forchlorfenuron (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fosthiazate (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('fuberidazole (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('furalaxyl (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('furathiocarbe (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('haloxyfop - R (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('haloxyfop including haloxyfop-R (HaloxyfopR methyl ester and haloxyfop-R expressed as haloxyfop-R) (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('haloxyfop-methyl (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('hexaconazole (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('hexazinone (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('héxythiazox (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('imazalil (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('imazamox', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('imazapyr', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('imazaquine', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('imazosulfuron (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('imidaclopride (A)', 4, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('indoxacarb (sum of indoxacarb and its R enantiomer) (A)', 4, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('iodosulfuron-methyl (iodosulfuron-methyl including salts, expressed as iodosulfuron-methyl) (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('iprobenfos (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('iprodione (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('iprovalicarbe (A)', 3, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('isoprothiolane (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('isoproturon (IPU) (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('isopyrazam (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('isoxaben (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('krésoxim-méthyl (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('lenacil (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('linuron (A)', 2, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('lufénuron (A)', 1, 0.02);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('mandipropamid (A)', 3, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('mépanipyrim (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('mesosulfuron-methyl (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('metaflumizone (sum of E- and Z- isomers) (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('metalaxyl and metalaxylM (metalaxyl including other mixtures of constituent isomers including metalaxyl-M (sum of isomers)) (A)', 3, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('métamitrone (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('metazachlor (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('metconazole (sum of isomers) (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('méthabenzthiazuron (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('méthamidophos (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('methiocarb (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('methiocarb (sum of methiocarb and methiocarb sulfoxide and sulfone, expressed as methiocarb) (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('methiocarb-sulfon (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('methiocarb-sulfoxide (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('metholachlor and metholachlor-S (metholachlor including other mixtures of constituent isomers including S-metholachlor (sum of isomers)) (A)', 2, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('methomyl (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('méthoxyfenozide (A)', 4, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('metobromuron (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('métosulame (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('métoxuron (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('metsulfuron-méthyl (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('molinate (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('monocrotophos (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('monolinuron (A)', 1, 0.02);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('myclobutanil (A)', 3, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('napropamide (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('nicosulfuron (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('nitenpyram (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('novaluron (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('nuarimol (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('ofurace (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('omethoate (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('oxadixyl (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('oxamyl (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('oxycarboxin (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('oxydemeton-methyl (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('oxydemeton-methyl (sum of oxydemeton-methyl and demeton-Smethylsulfone expressed as oxydemeton-methyl) (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('paclobutrazol (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('penconazole (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('pencycuron (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('penoxsulam (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('pethoxamid (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('phenmedipham (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('phenthoate (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('phosphamidon (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('phoxim (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('picolinafène (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('picoxystrobin (A)', 3, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('pinoxaden (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('pirimicarb (A)', 3, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('prochloraze (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('profenofos (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('promecarb (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('propamocarb (sum of propamocarb and its salt expressed as propamocarb) (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('propanil (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('propaquizafop (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('propazin (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('propham (IPC) (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('propiconazole (sum of isomers) (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('propoxur (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('propyzamide (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('proquinazid (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('prosulfocarbe (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('prosulfuron (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('prothioconazole: prothioconazole-dethio (sum of isomers) (A)', 3, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('pymétrozine (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('pyraclostrobine (A)', 3, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('pyraflufen-éthyl (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('pyrethrin I', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('pyrethrin II', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('pyrethrins', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('pyridafol', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('pyridalyl (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('pyridaphenthion (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('pyridate', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('Pyridate (sum of pyridate, its hydrolysis product CL 9673 (6-chloro-4hydroxy-3phenylpyridazin) and hydrolysable conjugates of CL 9673 expressed as p', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('pyrifénox (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('pyriméthanil (A)', 3, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('pyriofenone (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('quinclorac (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('quinmérac', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('quinoxyfène (A)', 3, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('quizalofop, incl. quizalofop-P (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('quizalofop-éthyl (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('rimsulfuron (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('roténone (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('séthoxydime (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('simazine (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('spinetoram (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('spinetoram I (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('spinetoram II (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('spinosad: sum of spinosyn A and spinosyn D, expressed as spinosad (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('spinosyn A (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('spinosyn D (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('spirotetramat (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('spirotetramat and its 4 metabolites BYI08330enol, BYI08330ketohydroxy, BYI08330monohydroxy, and BYI08330 enol-glucoside, expressed as spirotetramat (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('spirotetramat-enol (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('spirotetramat-enolglucoside (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('spirotetramat-keto-hydrox (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('spirotetramat-monohydrox (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('spiroxamine (sum of isomers) (A)', 3, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('sulfosulfuron (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('sulfoxaflor (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('tebuconazole (A)', 3, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('tébufenozide (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('tébufenpyrad (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('tepraloxydim (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('terbufos (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('terbufos-sulfon (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('terbufos-sulfoxide (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('tétraconazole (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('tetramethrine (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('thiabendazole (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('thiacloprid (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('thiametoxam (A)', 4, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('thifensulfuron-méthyle (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('thiobencarb (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('thiodicarb (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('thionazine (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('thiophanate-methyl (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('triadimefon and triadimenol (sum of triadimefon and triadimenol) (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('triadiméfone (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('triadimenol (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('triasulfuron (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('triazophos (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('trichlorfon (A)', 1, 0.02);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('tricyclazole (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('tridemorphe (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('trifloxystrobin (A)', 3, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('triflumizole (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('triflumuron (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('triforine (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('trinexapac (sum of trinexapac (acid) and its salts, expressed as trinexapac) (A)', 6, 0.02);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('triticonazole (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('valifenalate (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('vamidothion (A)', 1, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('zoxamide (A)', 3, 0.01);
INSERT INTO param_molecules_lms (nom, type_id, valeurTrace) VALUES ('RAS', 1, 0.00);

commit;