-- #######################################################################################################
-- INSERTION TABLE : param_espece
-- #######################################################################################################

INSERT INTO param_espece(genre_id,nom, nom2) VALUES (16,'Chénopode','Chénopode');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (49,'Terebinthus','Terebinthus');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (57,'Rhus spp.','Rhus spp.');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (1,'Apiaceae','Apiaceae');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (1,'Ombellifère','Ombellifère');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (32,'Berce','Berce');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (30,'Lierre','Lierre');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (15,'Chamaerops humilis','Chamaerops');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (15,'Chamaerops','Chamaerops');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (66,'Pissenlit','Pissenlit');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (39,'Matricaire','Matricaire');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (1,'Chardon','Chardon');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (64,'Seneçon','Seneçon');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (31,'Tournesol','Tournesol');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (1,'Pâquerette','Pâquerette');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (17,'Chicorée','Chicorée');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (33,'Epervière','Epervière');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (25,'Eupatoire','Eupatoire');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (6,'Aster','Aster');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (14,'Centaurée','Centaurée');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (1,'Asteraceae','Asteraceae');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (4,'Ambroisie','Ambroisie');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (5,'Armoise','Armoise');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (12,'Betulaceae','Betulaceae');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (23,'Vipérine','Vipérine');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (8,'Colza','Colza');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (8,'Crucifères','Brassicaceae');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (8,'Moutarde','Moutarde');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (8,'Brassicaceae','Brassicaceae');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (9,'Buddléia','Buddléia');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (35,'Jasione','Jasione');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (62,'Sureau','Sureau');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (1,'Caryophilaceae','Caryophilaceae');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (18,'Cistes','Cistes');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (18,'Cistaceae','Cistes');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (11,'Liseron','Liseron');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (20,'Cornouiller','Cornouiller');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (63,'Sédum','Sédum');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (1,'Carex','Carex');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (1,'Knautie','Knautie');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (24,'Bruyère cendrée','Bruyère cendrée');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (10,'Callune','Callune');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (41,'Mercuriale','Mercuriale');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (1,'Gléditschia','Gléditschia');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (43,'Sainfoin','Sainfoin');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (67,'Trefle des pres','Trèfle des prés');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (68,'Fève','Fève');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (67,'Trèfle blanc','Trèfle blanc');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (58,'Acacia','Acacia');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (7,'Psoralée','Psoralée');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (40,'Mélilot','Mélilot');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (1,'Genêt','Genêt');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (53,'Chêne','Chêne');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (27,'Hêtre','Hêtre');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (53,'Quercus','Chêne');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (13,'Chataignier','Châtaignier');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (1,'Fleurs','Fleurs');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (3,'Marronnier','Marronnier');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (48,'Seringat','Seringat');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (47,'Phacélie','Phacélie');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (34,'Millepertuis','Millepertuis');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (44,'Marjolaine','Marjolaine');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (1,'Liliacée','Liliacée');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (38,'Salicaire','Salicaire');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (37,'Tulipier de virginie','Tulipier de virginie');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (52,'Pyracantha','Pyracantha');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (29,'Frêne','Frêne');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (36,'Troène','Troène');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (45,'Papaver spp.','Papaver spp.');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (50,'Plantain','Plantain');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (1,'Poaceae','Poaceae');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (70,'Maïs','Maïs');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (60,'Oseille','Oseille');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (26,'Sarrasin','Sarrasin');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (46,'Persicaire','Persicaire');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (51,'Portulaca spp.','Portulaca spp.');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (19,'Clématite','Clématite');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (55,'Ranunculaceae','Ranunculaceae');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (42,'Nigelle','Nigelle');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (56,'Reseda','Reseda');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (54,'Nerprun','Nerprun');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (28,'Bourdaine','Bourdaine');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (1,'Fruitiers','Fruitiers');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (21,'Aubépine','Aubépine');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (1,'Rosaceae','Rosaceae');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (59,'Ronce','Ronce');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (61,'Saules','saules');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (2,'Erable','Erable');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (65,'Solenaceae','Solenaceae');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (65,'Morelle','Morelle');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (22,'Datura','Datura');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (69,'Vigne','Vigne');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (1,'Vigne vierge','Vigne vierge');
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Papaver',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Tamaris',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Tilleul',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Aigremoine eupatoire',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Luzerne',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Sumac',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Cornouiller sanguin',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Noyer',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Saule',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Pin',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Myosotis',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Lotier',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Graminées',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Cercis',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Thym',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Germandrée',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Paquerette',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Oléinées',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Renoncule',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Salsifis des prés',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Lamier',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Rhus',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Liliacées',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Pollen indéterminé',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Erica cinerea',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Composées',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Ombellifères',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Coquelicot',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Potentille',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Caprifoliacées',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Caryophyllacés',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Lin',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Sorbier',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Rosacées type prunus',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Hippocrèpis',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Géraniées',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Rosacées',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Figuier de Barbarie',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Ailanthe',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Laurier',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Bourrache',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Ilex',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Bombacacées',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Lillacées',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Cotoneaster',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Caryophyllacées',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Graminéa',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Polémoine',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Eucalyptus',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Onagre',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Lagerstromia',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Erynglum',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Portulaca',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Scabieuse',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Carthame',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Capucine',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Anacardiacées',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Houx',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Rumex',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Liriodendron',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Fagacées',null);
INSERT INTO param_espece(genre_id,nom, nom2) VALUES (null,'Pollen avorté',null);

commit;